server:
  port: 8081
spring:
#  aop:
#    auto: true
#    proxy-target-class: true
  datasource:
    name:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datiba?serverTimezone=Hongkong?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  type-aliases-package: com/datiba/entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #输出SQL命令

# jwt 配置
jwt:
  header: "Authorization"     # token 返回头部
  tokenPrefix: "Bearer "      # token 前缀
  secret: "datiba20201003180" # 私钥
  expireTime: 86400000   # token 的有效时间，单位是毫秒

# application.yml
image:
  upload:
    dir: "C:\\AppServ\\www\\datiba\\avatar"
  file:
    url:
      prefix: "http://localhost/datiba/avatar/"